baseURL = "https://juanbelieni.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
pagination.pagerSize = 10
summaryLength = 25

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
defaultMarkdownHandler = "pandoc"

[security]
[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^pandoc$']
