colorScheme = "sapphire"

enableSearch = false
enableCodeCopy = true
enableImageLazyLoading = true
enableQuicklink = true

[header]
layout = "hybrid"
showTitle = true

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = false

[homepage]
layout = "custom"
showRecent = true

[list]
showSummary = true
showTaxonomies = true


[article]
showTableOfContents = false
showTaxonomies = true
showReadingTime = false
showWordCount = true
showPagination = true
showAuthor = false

[verification]
google = "phQ3Cb5BAFwyJVkoyLnuTcdGHSpnQh3AzHU4UXQB1as"
