colorScheme = "congo"

enableSearch = false
enableCodeCopy = true
enableImageLazyLoading = true

[header]
layout = "hybrid"
showTitle = true

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "custom"
showRecent = true

[list]
showSummary = true
showTaxonomies = true


[article]
showTableOfContents = true
showTaxonomies = true
showReadingTime = false
showWordCount = true
showPagination = true
showAuthor = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[verification]
google = "d-YbOFu2nkyxHfUzEkdaGfe-8awI9qvFcCxNS5mXBD8"
